In [1]:
import pandas as pd

# Read Dataset


In [2]:
df = pd.read_csv('/Users/hanzpatrickyu/Documents/Jupyter/Fetal_Health/fetal_health.csv')

In [3]:
df

baseline value  accelerations  fetal_movement  uterine_contractions   
0              120.0          0.000           0.000                 0.000  \
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations   
0                   0.000                   0.0                       0.0  \
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability   
0                                73.0                                   0.5  \
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...   
0                                                  43.0       ...  \
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks   
0              62.0          126.0                        2.0  \
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                   

In [4]:
import sklearn.linear_model as linear_model

- Extracting feature matix AND labels

In [5]:
X = df[['baseline value', 'accelerations', 'fetal_movement', 'uterine_contractions', 'light_decelerations', 'severe_decelerations', 'prolongued_decelerations', 'abnormal_short_term_variability', 'mean_value_of_short_term_variability', 'percentage_of_time_with_abnormal_long_term_variability', 'mean_value_of_long_term_variability', 'histogram_width', 'histogram_min', 'histogram_max', 'histogram_number_of_peaks', 'histogram_number_of_zeroes', 'histogram_mode', 'histogram_mean', 'histogram_median', 'histogram_variance', 'histogram_tendency']].to_numpy()

In [6]:
y = df['fetal_health'].to_numpy()


- Scale the data

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()

In [9]:
X = scaler.fit_transform(X)

- Build the model

In [10]:
model = linear_model.LogisticRegression(penalty=None, max_iter=1000)

- fine-tune the parameters of the model

In [11]:
model.fit(X, y)

LogisticRegression(max_iter=1000, penalty=None)

In [12]:
model.coef_

array([[-0.4722165 ,  2.6097982 , -0.48119269,  0.58733227, -0.03972252,
         0.10931137, -1.0126092 , -1.57566747,  0.47080935, -0.62194699,
        -0.11713929, -0.06801277, -0.27203531, -0.59578673,  0.33945991,
        -0.16132638,  0.66721393, -1.18473034,  1.24633992, -1.10704851,
        -0.17250347],
       [-1.58372894, -1.25133427, -0.03830267, -0.19062974, -0.0355457 ,
        -0.31044592,  0.44287803, -0.06054587,  0.27267186, -0.18755346,
        -0.13249286, -0.10101988,  0.0985888 , -0.05689831,  0.74545955,
        -0.20479037, -0.56184819,  3.30165058,  0.47907886,  0.11919842,
        -0.00888334],
       [ 2.05594545, -1.35846393,  0.51949536, -0.39670253,  0.07526823,
         0.20113455,  0.56973118,  1.63621334, -0.74348121,  0.80950045,
         0.24963215,  0.16903265,  0.17344652,  0.65268503, -1.08491946,
         0.36611675, -0.10536574, -2.11692024, -1.72541878,  0.98785009,
         0.18138681]])

In [13]:
model.intercept_

array([ 5.27738278,  0.55617692, -5.8335597 ])

In [14]:
model.predict(X)

array([2., 1., 1., ..., 2., 2., 1.])

- seperate training and test set



In [15]:
import sklearn.model_selection as model_selection

In [16]:
X_train, X_test, y_train, y_test= model_selection.train_test_split(X, y, test_size=.2, random_state = 3)

- test_size=.2 mean test set is 20%

In [17]:
model = linear_model.LogisticRegression(penalty=None, verbose=True, max_iter = 1000)

In [18]:
model.fit(X_train, y_train)

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           66     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.86764D+03    |proj g|=  7.45333D+02

At iterate   50    f=  3.64012D+02    |proj g|=  4.47326D-01

At iterate  100    f=  3.63735D+02    |proj g|=  5.10880D-02

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   66    144    159      1     0     0   3.370D-03   3.637D+02
  F =   363.73315767038309     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
 This problem is unconstrained.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished


LogisticRegression(max_iter=1000, penalty=None, verbose=True)

In [19]:
model.coef_

array([[-0.36314969,  2.6322128 , -0.37443783,  0.54805964, -0.0333433 ,
        -0.37918146, -1.11334223, -1.52076086,  0.53002473, -0.6475739 ,
        -0.03345718, -0.09384227, -0.21181874, -0.55266365,  0.25417735,
        -0.1387648 ,  0.6234357 , -1.39005235,  1.31166008, -1.11119412,
        -0.19704125],
       [-1.50163326, -1.27216354, -0.12016439, -0.18824723, -0.07053437,
        -0.11147429,  0.52080784,  0.00770881,  0.32372016, -0.21890769,
        -0.07852998, -0.10269462,  0.04486813, -0.1490304 ,  0.79937604,
        -0.20562459, -0.63079992,  3.64295485,  0.29436588,  0.14433278,
        -0.13405403],
       [ 1.86478295, -1.36004926,  0.49460222, -0.35981241,  0.10387767,
         0.49065575,  0.59253439,  1.51305205, -0.85374489,  0.86648159,
         0.11198716,  0.19653689,  0.16695062,  0.70169405, -1.05355338,
         0.3443894 ,  0.00736422, -2.2529025 , -1.60602596,  0.96686134,
         0.33109528]])

In [20]:
model.intercept_

array([ 5.18810553,  0.52489333, -5.71299886])

In [21]:
y_pred = model.predict(X_test)
y_pred

array([1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1.,
       2., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1.,
       2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 3., 2., 1., 1., 1., 1., 3., 2., 1., 3., 1., 1., 1., 1., 2., 1.,
       3., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       3., 2., 3., 1., 1., 1., 2., 3., 1., 1., 1., 1., 1., 1., 1., 2., 1.,
       1., 2., 3., 1., 1., 1., 1., 1., 3., 1., 2., 2., 1., 1., 1., 3., 1.,
       2., 1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 3.,
       1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 3.,
       2., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 3., 1., 1., 1., 1., 1.,
       1., 3., 1., 1., 1.

y_test

- Compute performance metrics

In [22]:
import sklearn.metrics as metrics

- Accuracy, Recall, Precision

In [23]:
metrics.accuracy_score(y_test, y_pred)

0.8990610328638498

In [24]:
metrics.recall_score(y_test, y_pred, average='micro')

0.8990610328638498

- Confusion Matrix

In [25]:
metrics.confusion_matrix(y_test, y_pred)

array([[324,  17,   2],
       [ 15,  31,   4],
       [  1,   4,  28]])