# Importing required libraries

In [84]:
import pandas as pd

In [85]:
from sklearn.neural_network import MLPClassifier

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
import sklearn.model_selection as model_selection

In [88]:
from sklearn.preprocessing import StandardScaler

Load the dataset

In [89]:
df = pd.read_csv('fetal_health.csv')

Checks if the dataset loaded is correct

In [90]:
df

baseline value  accelerations  fetal_movement  uterine_contractions   
0              120.0          0.000           0.000                 0.000  \
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations   
0                   0.000                   0.0                       0.0  \
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability   
0                                73.0                                   0.5  \
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...   
0                                                  43.0       ...  \
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks   
0              62.0          126.0                        2.0  \
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                   

Splitting the dataset into input feature and target variable

In [91]:
X = df[['baseline value', 'accelerations', 'fetal_movement', 'uterine_contractions', 'light_decelerations', 'severe_decelerations', 'prolongued_decelerations', 'abnormal_short_term_variability', 'mean_value_of_short_term_variability', 'percentage_of_time_with_abnormal_long_term_variability', 'mean_value_of_long_term_variability', 'histogram_width', 'histogram_min', 'histogram_max', 'histogram_number_of_peaks', 'histogram_number_of_zeroes', 'histogram_mode', 'histogram_mean', 'histogram_median', 'histogram_variance', 'histogram_tendency']].to_numpy()

In [92]:
X

array([[1.20e+02, 0.00e+00, 0.00e+00, ..., 1.21e+02, 7.30e+01, 1.00e+00],
       [1.32e+02, 6.00e-03, 0.00e+00, ..., 1.40e+02, 1.20e+01, 0.00e+00],
       [1.33e+02, 3.00e-03, 0.00e+00, ..., 1.38e+02, 1.30e+01, 0.00e+00],
       ...,
       [1.40e+02, 1.00e-03, 0.00e+00, ..., 1.52e+02, 4.00e+00, 1.00e+00],
       [1.40e+02, 1.00e-03, 0.00e+00, ..., 1.51e+02, 4.00e+00, 1.00e+00],
       [1.42e+02, 2.00e-03, 2.00e-03, ..., 1.45e+02, 1.00e+00, 0.00e+00]])

In [93]:
y = df['fetal_health'].to_numpy()

In [94]:
y

array([2., 1., 1., ..., 2., 2., 1.])

In [95]:
scaler = StandardScaler()

In [96]:
X = scaler.fit_transform(X)

Splitting the data into training and testing sets

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=1)

Creating a neural network classifier with 1 hidden layer

In [98]:
clf = MLPClassifier(random_state=1, max_iter=1000)

Training the neural network classifier on the training data

In [99]:
clf.fit(X_train, y_train)

MLPClassifier(max_iter=1000, random_state=1)

Predicting the probabilities fo each class for test set

In [100]:
clf.predict_proba(X_test)

array([[1.00000000e+00, 1.92904803e-12, 1.37364435e-13],
       [1.00000000e+00, 2.68554574e-16, 1.62461453e-14],
       [3.31394141e-01, 6.68602766e-01, 3.09233440e-06],
       ...,
       [9.99971531e-01, 3.36796216e-11, 2.84685547e-05],
       [9.99042271e-01, 9.57702515e-04, 2.63433986e-08],
       [9.99999942e-01, 5.83432602e-08, 1.58353120e-11]])

Predicting target variable for the test set

In [101]:
y_pred = clf.predict(X_test)

In [102]:
y_pred

array([1., 1., 2., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       3., 1., 2., 1., 3., 2., 1., 1., 3., 1., 1., 1., 3., 2., 1., 1., 3.,
       3., 2., 1., 1., 2., 2., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 3., 2., 1., 1., 1., 2., 1., 2., 1., 1.,
       1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 3., 1., 1., 1.,
       1., 1., 1., 1., 1., 3., 1., 1., 2., 1., 2., 1., 3., 1., 1., 3., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 1., 1., 3., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1.,
       2., 1., 3., 2., 2., 1., 1., 1., 3., 1., 2., 1., 1., 2., 1., 1., 1.,
       3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.,
       1., 1., 3., 2., 1., 1., 1., 1., 1., 2., 1., 1., 3., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1., 1., 3., 1., 1., 1.,
       1., 2., 1., 1., 1.

Score, Accuracy, Recall, Confusion Matrix

In [103]:
import sklearn.metrics as metrics

In [104]:
clf.score(X_test, y_test)

0.9366197183098591

In [105]:
metrics.accuracy_score(y_test, y_pred)

0.9366197183098591

In [106]:
metrics.recall_score(y_test, y_pred, average='micro')

0.9366197183098591

In [107]:
metrics.confusion_matrix(y_test, y_pred)

array([[323,   8,   1],
       [ 11,  45,   3],
       [  2,   2,  31]], dtype=int64)